name: iOS starter workflow

on:
    push:
    branches: [ "main" ]
    pull_request:
    branches: [ "main" ]

jobs:
    build-and-test:
    name: Build and Test on iPhone Simulator
    runs-on: macos-13
    
    steps:
        - name: Checkout
        uses: actions/checkout@v3
        
        - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer
        
        - name: Build and Test
        env:
            scheme: 'Fitness (iOS)'
            platform: 'iOS Simulator'
            device: 'iPhone 14'
        run: |
            # Determine if the project uses a workspace or a project file and set the variables accordingly
            if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then
                filetype_parameter="workspace"
                file_to_build="`ls -A | grep -i \\.xcworkspace\$`";
            else
                filetype_parameter="project"
                file_to_build="`ls -A | grep -i \\.xcodeproj\$`";
            fi
            
            # Trim leading and trailing whitespace from the file_to_build variable
            file_to_build=$(echo $file_to_build | xargs)
            
            # Run xcodebuild with the determined scheme, file type (workspace or project), and destination
            xcodebuild -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device" clean test
